import { prisma, type Prisma } from "@tymra/db";
import Link from "next/link";
import { notFound } from "next/navigation";

import { CollectionIncidentActions } from "@/components/admin/CollectionIncidentActions";
import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminTable, StatusPill } from "@/components/admin/AdminTable";
import { adminDateLocale, type AdminLocale } from "@/lib/admin-i18n";
import { getAdminLocale } from "@/lib/server/admin-locale";

const runTabs = ["overview", "evidence", "output", "configuration", "audit"] as const;
type RunTab = (typeof runTabs)[number];

export default async function CollectionRunDetailPage({ params, searchParams }: { params: { runId: string }; searchParams: { tab?: string } }) {
  const locale = getAdminLocale();
  const text = copy(locale);
  const tab: RunTab = runTabs.includes(searchParams.tab as RunTab) ? searchParams.tab as RunTab : "overview";
  const tabText = runTabCopy(locale);
  const run = await prisma.collectionRun.findUnique({
    where: { id: params.runId },
    include: {
      dataSource: true,
      job: true,
      incident: true,
    },
  });
  if (!run || run.isDemo || !["PUBLIC", "MANUAL"].includes(run.dataSource.providerType) || !["PUBLIC_DATA", "MANUAL_IMPORT"].includes(run.dataSource.sourceType)) notFound();
  const start = run.startedAt ?? run.createdAt;
  const end = run.finishedAt ?? new Date();
  const [artifacts, artifactGroups, parserFailures, sourceEvents, sourceSignals, rates, crawlTargets, audits, schedules] = await Promise.all([
    prisma.rawArtifact.findMany({ where: { collectionRunId: run.id }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.rawArtifact.groupBy({ where: { collectionRunId: run.id }, by: ["artifactType"], _count: { _all: true } }),
    prisma.rawArtifact.count({ where: { collectionRunId: run.id, parserFailure: true } }),
    prisma.sourceEventOccurrence.findMany({ where: { lastCollectionRunId: run.id }, orderBy: { startsAt: "asc" }, take: 100, include: { _count: { select: { canonicalLinks: true } } } }),
    prisma.sourceMarketSignal.findMany({ where: { lastCollectionRunId: run.id }, orderBy: { startsAt: "asc" }, take: 100, include: { canonicalLink: { select: { marketSignalId: true } } } }),
    prisma.rateObservation.findMany({ where: { collectionRunId: run.id }, orderBy: { collectedAt: "desc" }, take: 100, include: { property: { select: { canonicalName: true } }, sellableUnit: { select: { officialName: true } } } }),
    prisma.sourceCrawlTarget.findMany({ where: { dataSourceId: run.dataSourceId, OR: [{ lastFetchedAt: { gte: start, lte: end } }, { lastSeenAt: { gte: start, lte: end } }, { lastErrorAt: { gte: start, lte: end } }] }, orderBy: { updatedAt: "desc" }, take: 50 }),
    prisma.auditEvent.findMany({ where: { OR: [{ entityType: "CollectionIncident", entityId: run.incident?.id ?? "none" }, { entityType: "CollectionRun", entityId: run.id }, ...(run.jobId ? [{ entityType: "Job", entityId: run.jobId }] : [])] }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.scheduleDefinition.findMany({ where: { jobType: { in: ["PUBLIC_DATA_COLLECTION", "EVENT_COLLECTION", "WEATHER_COLLECTION", "TRANSPORT_COLLECTION"] } }, select: { key: true, payload: true } }),
  ]);
  const artifactCount = artifactGroups.reduce((sum, item) => sum + item._count._all, 0);
  const challengeArtifacts = artifactGroups.filter((item) => item.artifactType.includes("CHALLENGE")).reduce((sum, item) => sum + item._count._all, 0);
  const linkedEvents = sourceEvents.filter((item) => item._count.canonicalLinks > 0).length;
  const linkedSignals = sourceSignals.filter((item) => item.canonicalLink !== null).length;
  const findings = diagnostics({ locale, status: run.status, errorCode: run.errorCode, errorSummary: run.errorSummary, artifactCount, parserFailures, challengeArtifacts, sourceEvents: sourceEvents.length, linkedEvents, sourceSignals: sourceSignals.length, linkedSignals });
  const metadata = jsonObject(run.dataSource.metadata);
  const scope = jsonObject(run.scope);
  const cooldownUntil = stringValue(scope.cooldownUntil) || stringValue(metadata.collectionCooldownUntil);
  const canRetry = Boolean(run.incident && !run.incident.retryJobId && schedules.some((schedule) => stringValue(jsonObject(schedule.payload).sourceId) === run.dataSource.key));
  const artifactRows = artifacts.map((artifact) => ({ id: artifact.id, href: `/admin/data-explorer/raw/${artifact.id}`, cells: { artifact: artifact.id, type: artifact.artifactType, parser: <StatusPill value={artifact.parserFailure ? "FAILED" : "SUCCEEDED"} locale={locale} />, content: artifact.containsSensitiveData ? text.sensitive : artifact.deletedAt ? text.deleted : text.available, created: date(artifact.createdAt, locale), expires: artifact.deletedAt ? text.deleted : date(artifact.expiresAt, locale) } }));
  const eventRows = sourceEvents.map((item) => ({ id: item.id, cells: { record: item.title, external: item.externalId, location: [item.city, item.region].filter(Boolean).join(", ") || "—", starts: date(item.startsAt, locale), status: <StatusPill value={item.status} locale={locale} />, lineage: item._count.canonicalLinks ? <StatusPill value="LINKED" locale={locale} /> : <StatusPill value="UNLINKED" locale={locale} /> } }));
  const signalRows = sourceSignals.map((item) => ({ id: item.id, cells: { record: item.title, external: item.externalId, location: item.region, starts: date(item.startsAt, locale), status: <StatusPill value={item.direction} locale={locale} />, lineage: item.canonicalLink ? <StatusPill value="LINKED" locale={locale} /> : <StatusPill value="UNLINKED" locale={locale} /> } }));

  const overview = <><section className={`run-diagnostics ${findings.some((item) => item.tone === "danger") ? "has-danger" : findings.some((item) => item.tone === "warning") ? "has-warning" : "is-clear"}`}><div className="collection-section-header"><div><h2>{text.diagnostics}</h2><p>{text.diagnosticsBody}</p></div></div><ul>{findings.map((finding) => <li key={finding.title} className={finding.tone}><strong>{finding.title}</strong><span>{finding.body}</span></li>)}</ul></section><section><h2>{text.execution}</h2><dl className="detail-list"><div><dt>{text.source}</dt><dd><Link href={`/admin/data-sources/${run.dataSource.key}`}>{run.dataSource.name}</Link><small>{run.dataSource.key}</small></dd></div><div><dt>{text.mode}</dt><dd>{run.mode}</dd></div><div><dt>{text.started}</dt><dd>{date(run.startedAt, locale)}</dd></div><div><dt>{text.finished}</dt><dd>{date(run.finishedAt, locale)}</dd></div><div><dt>{text.error}</dt><dd>{[run.errorCode, run.errorSummary].filter(Boolean).join(" · ") || "—"}</dd></div><div><dt>{text.correlation}</dt><dd className="code-value">{run.correlationId ?? "—"}</dd></div></dl></section><section><h2>{text.sourceHealth}</h2><dl className="detail-list"><div><dt>{text.enabled}</dt><dd><StatusPill value={run.dataSource.enabled ? "ENABLED" : "PAUSED"} locale={locale} /></dd></div><div><dt>{text.health}</dt><dd><StatusPill value={run.dataSource.operationalStatus} locale={locale} /></dd></div><div><dt>{text.lastSuccess}</dt><dd>{date(run.dataSource.lastSuccessAt, locale)}</dd></div><div><dt>{text.errorRate}</dt><dd>{Math.round(run.dataSource.errorRate * 100)}%</dd></div><div><dt>{text.cooldown}</dt><dd>{cooldownUntil ? date(new Date(cooldownUntil), locale) : "—"}</dd></div></dl><Link className="admin-secondary-action" href={`/admin/data-sources/${run.dataSource.key}`}>{text.manageSource}</Link></section></>;
  const evidence = <><section><h2>{text.artifacts}</h2><AdminTable columns={[{ key: "artifact", label: text.artifact }, { key: "type", label: text.type }, { key: "parser", label: text.parser }, { key: "content", label: text.content }, { key: "created", label: text.created }, { key: "expires", label: text.expires }]} rows={artifactRows} emptyTitle={text.noArtifacts} emptyBody={text.noArtifactsBody} /></section><section><h2>{text.targets}</h2><AdminTable columns={[{ key: "url", label: "URL" }, { key: "kind", label: text.kind }, { key: "status", label: text.status }, { key: "failures", label: text.failures }, { key: "fetched", label: text.fetched }, { key: "error", label: text.error }]} rows={crawlTargets.map((target) => ({ id: target.id, cells: { url: <span className="code-value">{target.url}</span>, kind: target.kind, status: <StatusPill value={target.status} locale={locale} />, failures: target.consecutiveFailures, fetched: date(target.lastFetchedAt, locale), error: target.lastErrorCode ?? "—" } }))} emptyTitle={text.noTargets} emptyBody={text.noTargetsBody} /></section></>;
  const output = <section><h2>{text.produced}</h2><div className="run-record-tabs"><h3>{text.events} <span>{sourceEvents.length}</span></h3><AdminTable columns={[{ key: "record", label: text.record }, { key: "external", label: text.external }, { key: "location", label: text.location }, { key: "starts", label: text.starts }, { key: "status", label: text.status }, { key: "lineage", label: text.lineage }]} rows={eventRows} emptyTitle={text.noEvents} emptyBody={text.noRecordsBody} /><h3>{text.signals} <span>{sourceSignals.length}</span></h3><AdminTable columns={[{ key: "record", label: text.record }, { key: "external", label: text.external }, { key: "location", label: text.location }, { key: "starts", label: text.starts }, { key: "status", label: text.status }, { key: "lineage", label: text.lineage }]} rows={signalRows} emptyTitle={text.noSignals} emptyBody={text.noRecordsBody} />{rates.length ? <><h3>{text.rates} <span>{rates.length}</span></h3><ul className="run-rate-list">{rates.map((rate) => <li key={rate.id}><strong>{rate.property.canonicalName}</strong><span>{rate.sellableUnit.officialName}</span><span>{new Intl.NumberFormat(adminDateLocale(locale), { style: "currency", currency: "NZD" }).format(rate.nzdTotalMinor / 100)}</span></li>)}</ul></> : null}</div></section>;
  const configuration = <><section><h2>{text.job}</h2>{run.job ? <><dl className="detail-list"><div><dt>ID</dt><dd className="code-value">{run.job.id}</dd></div><div><dt>{text.type}</dt><dd>{run.job.type}</dd></div><div><dt>{text.queue}</dt><dd>{run.job.queueName}</dd></div><div><dt>{text.jobStatus}</dt><dd><StatusPill value={run.job.status} locale={locale} /></dd></div><div><dt>{text.attempts}</dt><dd>{run.job.attemptCount} / {run.job.maxAttempts}</dd></div><div><dt>{text.worker}</dt><dd>{run.job.lockedBy ?? "—"}</dd></div><div><dt>{text.lease}</dt><dd>{date(run.job.leaseExpiresAt, locale)}</dd></div><div><dt>{text.jobError}</dt><dd>{[run.job.lastErrorCode, run.job.lastErrorMessage].filter(Boolean).join(" · ") || "—"}</dd></div></dl><h3>{text.payload}</h3><pre className="evidence-block data-payload">{JSON.stringify(run.job.payload, null, 2)}</pre></> : <div className="admin-empty compact"><h3>{text.noJob}</h3><p>{text.noJobBody}</p></div>}</section><section><h2>{text.scope}</h2><pre className="evidence-block data-payload">{JSON.stringify(run.scope, null, 2)}</pre></section></>;
  const audit = <section><h2>{text.audit}</h2>{audits.length ? <ol className="audit-timeline">{audits.map((event) => <li key={event.id}><strong>{event.eventType.replaceAll("_", " ")}</strong><span>{date(event.createdAt, locale)}</span></li>)}</ol> : <p className="empty-inline">{text.noAudit}</p>}</section>;
  const content: Record<RunTab, React.ReactNode> = { overview, evidence, output, configuration, audit };

  return <section className="admin-page collection-run-detail">
    <AdminPageHeader title={text.title} description={run.id} actions={<div className="header-pills"><StatusPill value={run.status} locale={locale} />{run.incident ? <StatusPill value={run.incident.status} locale={locale} /> : null}<Link className="button button-secondary" href="/admin/collection-runs">{text.back}</Link></div>} />
    <dl className="run-summary"><div><dt>{text.duration}</dt><dd>{duration(run.startedAt, run.finishedAt, locale)}</dd></div><div><dt>{text.records}</dt><dd>{run.successCount}<span> / {run.failureCount}</span></dd></div><div><dt>{text.rawEvidence}</dt><dd>{artifactCount}<span> / {parserFailures}</span></dd></div><div><dt>{text.lineage}</dt><dd>{linkedEvents + linkedSignals}<span> / {sourceEvents.length + sourceSignals.length}</span></dd></div><div><dt>{text.crawlTargets}</dt><dd>{crawlTargets.length}</dd></div></dl>
    <nav className="data-explorer-tabs run-detail-tabs" aria-label={tabText.sections}>{runTabs.map((item) => <Link key={item} href={`/admin/collection-runs/${run.id}?tab=${item}`} aria-current={tab === item ? "page" : undefined}>{tabText.tabs[item]}{item === "evidence" ? <span>{artifactCount}</span> : item === "output" ? <span>{sourceEvents.length + sourceSignals.length + rates.length}</span> : item === "audit" ? <span>{audits.length}</span> : null}</Link>)}</nav>
    <div className="workspace-grid run-tab-workspace"><div className="workspace-main">{content[tab]}</div><aside className="workspace-side is-sticky"><section><h2>{text.incident}</h2>{run.incident ? <><div className="incident-heading"><StatusPill value={run.incident.severity} locale={locale} /><StatusPill value={run.incident.status} locale={locale} /></div><h3>{run.incident.title}</h3><p className="recommendation">{run.incident.summary}</p><dl className="detail-list"><div><dt>{text.category}</dt><dd>{run.incident.category}</dd></div><div><dt>{text.retryJob}</dt><dd className="code-value">{run.incident.retryJobId ?? "—"}</dd></div><div><dt>{text.resolution}</dt><dd>{[run.incident.resolutionAction, run.incident.resolutionReason].filter(Boolean).join(" · ") || "—"}</dd></div></dl>{["OPEN", "IN_PROGRESS"].includes(run.incident.status) ? <CollectionIncidentActions locale={locale} incidentId={run.incident.id} status={run.incident.status} canRetry={canRetry} canPause={run.dataSource.providerType === "PUBLIC" && run.dataSource.enabled} /> : null}</> : <div className="admin-empty compact"><h3>{text.noIncident}</h3><p>{text.noIncidentBody}</p></div>}</section></aside></div>
  </section>;
}

type DiagnosticInput = { locale: AdminLocale; status: string; errorCode: string | null; errorSummary: string | null; artifactCount: number; parserFailures: number; challengeArtifacts: number; sourceEvents: number; linkedEvents: number; sourceSignals: number; linkedSignals: number };
function diagnostics(input: DiagnosticInput) { const text = copy(input.locale); const items: Array<{ tone: "danger" | "warning" | "clear"; title: string; body: string }> = []; if (input.status === "FAILED") items.push({ tone: "danger", title: text.runFailed, body: [input.errorCode, input.errorSummary].filter(Boolean).join(" · ") || text.reviewEvidence }); else if (input.status === "PARTIAL") items.push({ tone: "warning", title: text.runPartial, body: [input.errorCode, input.errorSummary].filter(Boolean).join(" · ") || text.reviewEvidence }); if (input.challengeArtifacts) items.push({ tone: "danger", title: text.challenge, body: text.challengeBody.replace("{count}", String(input.challengeArtifacts)) }); if (input.parserFailures) items.push({ tone: "warning", title: text.parserFailure, body: text.parserFailureBody.replace("{count}", String(input.parserFailures)) }); const unlinked = input.sourceEvents - input.linkedEvents + input.sourceSignals - input.linkedSignals; if (unlinked) items.push({ tone: "warning", title: text.lineageGap, body: text.lineageGapBody.replace("{count}", String(unlinked)) }); if (!input.artifactCount && ["FAILED", "PARTIAL"].includes(input.status)) items.push({ tone: "warning", title: text.noFailureEvidence, body: text.noFailureEvidenceBody }); if (!items.length) items.push({ tone: "clear", title: text.clear, body: text.clearBody }); return items; }
function jsonObject(value: Prisma.JsonValue): Record<string, Prisma.JsonValue> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, Prisma.JsonValue> : {}; }
function stringValue(value: Prisma.JsonValue | undefined) { return typeof value === "string" ? value : ""; }
function date(value: Date | null, locale: AdminLocale) { return value && !Number.isNaN(value.getTime()) ? value.toLocaleString(adminDateLocale(locale), { dateStyle: "medium", timeStyle: "short", timeZone: "Pacific/Auckland" }) : "—"; }
function duration(start: Date | null, end: Date | null, locale: AdminLocale) { if (!start) return "—"; const seconds = Math.max(0, Math.round(((end ?? new Date()).getTime() - start.getTime()) / 1_000)); if (seconds < 60) return locale === "zh" ? `${seconds} 秒` : `${seconds}s`; const minutes = Math.floor(seconds / 60); const remainder = seconds % 60; return locale === "zh" ? `${minutes} 分 ${remainder} 秒` : `${minutes}m ${remainder}s`; }
function runTabCopy(locale: AdminLocale) { return locale === "zh" ? { sections: "运行详情栏目", tabs: { overview: "概览", evidence: "证据", output: "产出", configuration: "配置", audit: "审计" } } : { sections: "Run detail sections", tabs: { overview: "Overview", evidence: "Evidence", output: "Output", configuration: "Configuration", audit: "Audit" } }; }
function copy(locale: AdminLocale) { return locale === "zh" ? zh : en; }
const en = { title: "Collection Run Detail", back: "Back to collection runs", duration: "Duration", records: "Success / failure", rawEvidence: "Evidence / parser failures", lineage: "Lineage coverage", crawlTargets: "Crawl targets", diagnostics: "Run diagnostics", diagnosticsBody: "Derived checks across execution state, evidence and canonical lineage.", execution: "Execution", source: "Data source", mode: "Mode", started: "Started", finished: "Finished", error: "Error", correlation: "Correlation ID", job: "Queue job", type: "Type", queue: "Queue", jobStatus: "Job status", attempts: "Attempts", worker: "Worker", lease: "Lease expires", jobError: "Job error", payload: "Job payload", noJob: "No linked queue job", noJobBody: "This run was created directly or predates durable job linkage.", scope: "Effective scope and counters", artifacts: "Raw evidence", artifact: "Artifact", parser: "Parser", content: "Content", created: "Created", expires: "Expires", sensitive: "Sensitive", deleted: "Deleted", available: "Available", noArtifacts: "No raw evidence", noArtifactsBody: "This run did not persist raw evidence.", produced: "Produced records and lineage", events: "Source event occurrences", signals: "Source market signals", rates: "Rate observations", record: "Record", external: "External ID", location: "Location", starts: "Starts", status: "Status", noEvents: "No source events", noSignals: "No source signals", noRecordsBody: "This run did not produce records of this type.", targets: "Crawl frontier touched by this run", kind: "Kind", failures: "Failures", fetched: "Fetched", noTargets: "No crawl targets", noTargetsBody: "No frontier records were touched during this run window.", incident: "Operational incident", category: "Category", retryJob: "Retry job", resolution: "Resolution", noIncident: "No incident", noIncidentBody: "This run completed without an open operational incident.", sourceHealth: "Source health", enabled: "Collection state", health: "Health", lastSuccess: "Last success", errorRate: "Error rate", cooldown: "Cooldown until", manageSource: "Manage source", audit: "Incident audit", noAudit: "No administrator actions recorded.", runFailed: "Collection failed", runPartial: "Collection partially completed", reviewEvidence: "Review the run evidence and source state.", challenge: "Browser challenge detected", challengeBody: "{count} challenge artifact(s) were retained for manual review.", parserFailure: "Parser failures", parserFailureBody: "{count} artifact(s) were marked as parser failures.", lineageGap: "Canonical lineage gap", lineageGapBody: "{count} source record(s) are not linked to canonical records.", noFailureEvidence: "Failure has no raw evidence", noFailureEvidenceBody: "The error can only be diagnosed from runtime metadata.", clear: "No diagnostic issue detected", clearBody: "Execution, evidence and lineage checks passed for the persisted output." };
const zh: typeof en = { title: "采集运行详情", back: "返回采集运行", duration: "耗时", records: "成功 / 失败", rawEvidence: "证据 / 解析失败", lineage: "血缘覆盖", crawlTargets: "抓取目标", diagnostics: "运行诊断", diagnosticsBody: "综合执行状态、原始证据和标准化血缘生成的检查结果。", execution: "执行信息", source: "数据来源", mode: "模式", started: "开始时间", finished: "结束时间", error: "错误", correlation: "关联 ID", job: "队列任务", type: "类型", queue: "队列", jobStatus: "任务状态", attempts: "尝试次数", worker: "Worker", lease: "租约到期", jobError: "任务错误", payload: "任务载荷", noJob: "没有关联队列任务", noJobBody: "此次运行由直接命令创建，或早于持久化任务关联。", scope: "实际范围和计数器", artifacts: "原始证据", artifact: "证据", parser: "解析器", content: "内容", created: "创建时间", expires: "过期时间", sensitive: "敏感", deleted: "已删除", available: "可查看", noArtifacts: "没有原始证据", noArtifactsBody: "此次运行没有保存原始证据。", produced: "产出记录和血缘", events: "来源事件场次", signals: "来源市场信号", rates: "价格观测", record: "记录", external: "外部 ID", location: "地点", starts: "开始", status: "状态", noEvents: "没有来源事件", noSignals: "没有来源信号", noRecordsBody: "此次运行没有产生此类记录。", targets: "此次运行涉及的抓取目标", kind: "类型", failures: "失败次数", fetched: "抓取时间", noTargets: "没有抓取目标", noTargetsBody: "此次运行时间范围内没有触及抓取前沿记录。", incident: "运营异常", category: "异常类别", retryJob: "重试任务", resolution: "处理结果", noIncident: "没有异常", noIncidentBody: "此次运行完成且没有未关闭的运营异常。", sourceHealth: "来源健康", enabled: "采集状态", health: "健康状态", lastSuccess: "最近成功", errorRate: "错误率", cooldown: "冷却至", manageSource: "管理来源", audit: "异常审计", noAudit: "暂无管理员处置记录。", runFailed: "采集失败", runPartial: "采集部分完成", reviewEvidence: "需要检查运行证据和来源状态。", challenge: "检测到浏览器挑战", challengeBody: "已保留 {count} 个挑战证据供人工判断。", parserFailure: "解析失败", parserFailureBody: "有 {count} 个证据被标记为解析失败。", lineageGap: "标准化血缘缺口", lineageGapBody: "有 {count} 条来源记录尚未关联标准记录。", noFailureEvidence: "失败但没有原始证据", noFailureEvidenceBody: "目前只能通过运行元数据诊断此错误。", clear: "未发现诊断问题", clearBody: "已保存产出的执行、证据和血缘检查均通过。" };
