packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@ulixee/chrome-136-0": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
