"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import type { AdminLocale } from "@/lib/admin-i18n";
import { serviceErrorCopy } from "@/lib/service-operation-copy";
type Preview = { previewHash: string; previousUnitId: string; targetUnitId: string; quarantinedObservations: number; withdrawnResults: number; affectedCheckIds: string[] };
export function MappingRepairForm({ listingId, units, locale }: { listingId: string; units: { id: string; officialName: string }[]; locale: AdminLocale }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [prepared, setPrepared] = useState<Record<string, unknown> | null>(null); const [preview, setPreview] = useState<Preview | null>(null);
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => setHydrated(true), []);
  async function call(action: "PREVIEW" | "REPAIR", input: unknown) { const response = await fetch(`/api/v1/admin/listings/${listingId}/repair`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, input }) }); const result = await response.json(); if (!response.ok) throw new Error(serviceErrorCopy(locale, result.error?.code)); return result.data; }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const input = { ...Object.fromEntries(new FormData(event.currentTarget)), commandId: crypto.randomUUID() }; const result = await call("PREVIEW", input); setPreview(result); setPrepared({ ...input, previewHash: result.previewHash }); } catch(error) { setMessage(error instanceof Error ? error.message : serviceErrorCopy(locale)); } finally { setBusy(false); } }
  async function commit() { setBusy(true); setMessage(""); try { await call("REPAIR", prepared); setPreview(null); setPrepared(null); setMessage(locale === "zh" ? "映射已修复，错误观测已隔离，受影响请求已进入恢复队列。" : "Mapping repaired, incorrect observations quarantined, affected requests routed for recovery."); router.refresh(); } catch(error) { setMessage(error instanceof Error ? error.message : serviceErrorCopy(locale)); } finally { setBusy(false); } }
  return <><form method="post" data-hydrated={hydrated} className="incident-action-form" onSubmit={submit} onChange={() => { setPreview(null); setPrepared(null); }}><p>{locale === "zh" ? "须由同一来源的完整身份原始证据证明目标单位。客户原输入保持，历史结果和观测保留。" : "Complete same-source identity evidence must prove the canonical unit. Original customer inputs and historical results remain."}</p><label>{locale === "zh" ? "已证实的标准单位" : "Proven canonical unit"}<select name="targetUnitId" required>{units.map(unit => <option key={unit.id} value={unit.id}>{unit.officialName} · {unit.id}</option>)}</select></label><label>{locale === "zh" ? "原始身份数据证据 ID" : "Raw identity evidence ID"}<input name="evidenceArtifactId" required /></label><label>{locale === "zh" ? "修复原因" : "Repair reason"}<textarea name="reason" required minLength={3} maxLength={1000} /></label><button className="button button-secondary" disabled={busy || !hydrated}>{locale === "zh" ? "核验证据与影响" : "Verify evidence and impact"}</button></form>{preview ? <section className="admin-detail-section"><p>{preview.previousUnitId} → {preview.targetUnitId}</p><p>{locale === "zh" ? `隔离 ${preview.quarantinedObservations} 条观测，撤回 ${preview.withdrawnResults} 份受影响结果，涉及 ${preview.affectedCheckIds.length} 个请求。` : `Quarantine ${preview.quarantinedObservations} observations, withdraw ${preview.withdrawnResults} affected results, route ${preview.affectedCheckIds.length} requests.`}</p><button className="button button-primary" disabled={busy || !hydrated} onClick={commit}>{locale === "zh" ? "按此预览修复" : "Apply this reviewed repair"}</button></section> : null}<p role="status">{message}</p></>;
}
