import type { Environment } from "@tymra/config";
import type { PublicDataAdapter } from "@tymra/providers/types";
import type { DirectEventPageLoader } from "./contracts";
import type * as requests from "./requests";
import type * as pricing from "./pricing";
import type * as collection_coordinator from "./collection/coordinator";
import type * as collection_eventfinda from "./collection/eventfinda";
import type * as collection_ticketmaster from "./collection/ticketmaster";
import type * as collection_regional_events from "./collection/regional-events";
import type * as collection_browser_connectors from "./collection/browser-connectors";
import type * as collection_persistence from "./collection/persistence";
import type * as catalog from "./catalog";
import type * as operations from "./operations";

export type WorkerContext = {
  readonly environment: Environment;
  readonly publicAdapters: Record<string, PublicDataAdapter>;
  readonly directEventPageLoader?: DirectEventPageLoader;
  createPreview: typeof requests.createPreview;
  createFormalAnalysis: typeof requests.createFormalAnalysis;
  validatePriceCheckOtaListing: typeof pricing.validatePriceCheckOtaListing;
  validateFixturePriceCheckListing: typeof pricing.validateFixturePriceCheckListing;
  markOtaListingSourceUnavailable: typeof pricing.markOtaListingSourceUnavailable;
  markOtaListingConflict: typeof pricing.markOtaListingConflict;
  collectPriceCheckOtaRate: typeof pricing.collectPriceCheckOtaRate;
  discoverAndCollectPriceCheckComparables: typeof pricing.discoverAndCollectPriceCheckComparables;
  confirmAnalysis: typeof requests.confirmAnalysis;
  getAnalysis: typeof requests.getAnalysis;
  getResult: typeof requests.getResult;
  cancelAnalysis: typeof requests.cancelAnalysis;
  resendResultNotification: typeof requests.resendResultNotification;
  collectAnalysis: typeof pricing.collectAnalysis;
  buildCompetitorSet: typeof pricing.buildCompetitorSet;
  buildSnapshots: typeof pricing.buildSnapshots;
  analyseSnapshot: typeof pricing.analyseSnapshot;
  collectSource: typeof collection_coordinator.collectSource;
  assertLocalAcceptanceAllowed: typeof collection_coordinator.assertLocalAcceptanceAllowed;
  assertSourceCollectionAllowed: typeof collection_coordinator.assertSourceCollectionAllowed;
  metServiceCollectionState: typeof collection_coordinator.metServiceCollectionState;
  previousChristchurchScan: typeof collection_coordinator.previousChristchurchScan;
  persistNormalisedSignal: typeof collection_persistence.persistNormalisedSignal;
  resumeOrCreateBrowserCollectionRun: typeof collection_coordinator.resumeOrCreateBrowserCollectionRun;
  collectArgusEventSource: typeof collection_regional_events.collectArgusEventSource;
  collectRbnzFxSource: typeof collection_regional_events.collectRbnzFxSource;
  collectTicketmasterSource: typeof collection_ticketmaster.collectTicketmasterSource;
  assertTicketmasterSourceAllowed: typeof collection_ticketmaster.assertTicketmasterSourceAllowed;
  collectEventfindaSource: typeof collection_eventfinda.collectEventfindaSource;
  assertEventfindaSourceAllowed: typeof collection_eventfinda.assertEventfindaSourceAllowed;
  executeEventfindaBrowserTask: typeof collection_browser_connectors.executeEventfindaBrowserTask;
  executeOurAucklandBrowserTask: typeof collection_browser_connectors.executeOurAucklandBrowserTask;
  executeTicketmasterBrowserTask: typeof collection_browser_connectors.executeTicketmasterBrowserTask;
  executeDirectHttpEventTask: typeof collection_browser_connectors.executeDirectHttpEventTask;
  loadDirectEventPage: typeof collection_browser_connectors.loadDirectEventPage;
  persistDirectHttpEvidence: typeof collection_persistence.persistDirectHttpEvidence;
  executeRbnzFxBrowserTask: typeof collection_browser_connectors.executeRbnzFxBrowserTask;
  executeSkiSeasonArgusTask: typeof collection_browser_connectors.executeSkiSeasonArgusTask;
  executeAviationArgusTask: typeof collection_browser_connectors.executeAviationArgusTask;
  executePublicMarketArgusTask: typeof collection_browser_connectors.executePublicMarketArgusTask;
  executeLincolnKeyDatesBrowserTask: typeof collection_browser_connectors.executeLincolnKeyDatesBrowserTask;
  executeCouncilArgusTask: typeof collection_browser_connectors.executeCouncilArgusTask;
  executePriorityArgusEventTask: typeof collection_browser_connectors.executePriorityArgusEventTask;
  persistArgusConnectorPayload: typeof collection_persistence.persistArgusConnectorPayload;
  persistArgusEvidence: typeof collection_persistence.persistArgusEvidence;
  markArgusEvidenceParserFailure: typeof collection_persistence.markArgusEvidenceParserFailure;
  argusHealth: typeof operations.argusHealth;
  syncCollectionIncidentSafely: typeof operations.syncCollectionIncidentSafely;
  sourceHealth: typeof operations.sourceHealth;
  otaHealth: typeof operations.otaHealth;
  retentionCleanup: typeof operations.retentionCleanup;
  activateSource: typeof operations.activateSource;
  collectProductionOta: typeof catalog.collectProductionOta;
  refreshCatalog: typeof catalog.refreshCatalog;
  refreshPanel: typeof catalog.refreshPanel;
  collectPanelMemberRate: typeof catalog.collectPanelMemberRate;
  refreshOtaMarketSignals: typeof catalog.refreshOtaMarketSignals;
  suspendSource: typeof operations.suspendSource;
  sourceSchedulePlan: typeof operations.sourceSchedulePlan;
  configureSourceSchedules: typeof operations.configureSourceSchedules;
  enqueueOperationalJob: typeof operations.enqueueOperationalJob;
  health: typeof operations.health;
  createRequest: typeof requests.createRequest;
  resolveAndPersistInput: typeof requests.resolveAndPersistInput;
  createBackingPriceCheck: typeof requests.createBackingPriceCheck;
  ensureQueryPlan: typeof requests.ensureQueryPlan;
  enqueueCollection: typeof requests.enqueueCollection;
  enqueueWorkerJob: typeof requests.enqueueWorkerJob;
  requireReadyIdentity: typeof requests.requireReadyIdentity;
  setStatus: typeof requests.setStatus;
  failBusiness: typeof requests.failBusiness;
  requireFixtureSource: typeof pricing.requireFixtureSource;
  ensureCollectionProfile: typeof pricing.ensureCollectionProfile;
  ensureFixtureCompetitors: typeof pricing.ensureFixtureCompetitors;
  ensureStayQueryForDate: typeof pricing.ensureStayQueryForDate;
  analysisObservationIds: typeof pricing.analysisObservationIds;
  collectPublicSignals: typeof collection_coordinator.collectPublicSignals;
  publishFormalResult: typeof pricing.publishFormalResult;
  publishObservedOnlyResult: typeof pricing.publishObservedOnlyResult;
  enforceWorkerLimits: typeof requests.enforceWorkerLimits;
  recordWorkerUsage: typeof requests.recordWorkerUsage;
  recordAbuseDecision: typeof requests.recordAbuseDecision;
  adapterContext: typeof collection_coordinator.adapterContext;
  publicAdapterContext: typeof collection_coordinator.publicAdapterContext;
  persistNormalisedEvent: typeof collection_persistence.persistNormalisedEvent;
  persistNormalisedEvents: typeof collection_persistence.persistNormalisedEvents;
  persistEventSignals: typeof collection_persistence.persistEventSignals;
  persistNormalisedEventCached: typeof collection_persistence.persistNormalisedEventCached;
  reconcileCanonicalEventImpact: typeof collection_persistence.reconcileCanonicalEventImpact;
  fixtureEnabled: typeof pricing.fixtureEnabled;
};
