import { prisma, type Prisma } from "@tymra/db";
import Link from "next/link";
import { notFound } from "next/navigation";

import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminTable, StatusPill, type AdminColumn, type AdminRow } from "@/components/admin/AdminTable";
import { adminDateLocale, type AdminLocale } from "@/lib/admin-i18n";
import { getAdminLocale } from "@/lib/server/admin-locale";

const tabs = ["overview", "runs", "schedules", "frontier", "data"] as const;
type SourceTab = (typeof tabs)[number];

export default async function DataSourceDetailPage({ params, searchParams }: { params: { sourceKey: string }; searchParams: { tab?: string } }) {
  const locale = getAdminLocale();
  const text = copy(locale);
  const tab = tabs.includes(searchParams.tab as SourceTab) ? searchParams.tab as SourceTab : "overview";
  const source = await prisma.dataSource.findUnique({ where: { key: params.sourceKey }, include: { capabilities: { where: { enabled: true, validTo: null }, orderBy: [{ capability: "asc" }, { version: "desc" }] }, _count: { select: { collectionRuns: true, sourceEvents: true, sourceEventOccurrences: true, sourceMarketSignals: true, observations: true, crawlTargets: true } } } });
  if (!source || source.isDemo) notFound();
  const [runs, schedules, frontier, recentEvents, recentSignals] = await Promise.all([
    prisma.collectionRun.findMany({ where: { dataSourceId: source.id, isDemo: false }, orderBy: { createdAt: "desc" }, take: 50, include: { incident: true } }),
    prisma.scheduleDefinition.findMany({ where: { jobType: { in: ["PUBLIC_DATA_COLLECTION", "EVENT_COLLECTION", "WEATHER_COLLECTION", "TRANSPORT_COLLECTION"] } }, orderBy: { key: "asc" } }),
    prisma.sourceCrawlTarget.findMany({ where: { dataSourceId: source.id }, orderBy: [{ active: "desc" }, { updatedAt: "desc" }], take: 100 }),
    prisma.sourceEventOccurrence.findMany({ where: { dataSourceId: source.id, isDemo: false }, orderBy: { lastSeenAt: "desc" }, take: 10 }),
    prisma.sourceMarketSignal.findMany({ where: { dataSourceId: source.id, isDemo: false }, orderBy: { lastSeenAt: "desc" }, take: 10 }),
  ]);
  const sourceSchedules = schedules.filter((schedule) => stringValue(jsonObject(schedule.payload).sourceId) === source.key);
  const lastRun = runs[0];
  const tabContent: Record<SourceTab, React.ReactNode> = {
    overview: <div className="source-overview-grid"><section><h2>{text.operationalState}</h2><dl className="detail-list"><div><dt>{text.collectionState}</dt><dd><StatusPill value={source.enabled ? "ENABLED" : "PAUSED"} locale={locale} /></dd></div><div><dt>{text.health}</dt><dd><StatusPill value={source.operationalStatus} locale={locale} /></dd></div><div><dt>{text.lastSuccess}</dt><dd>{date(source.lastSuccessAt, locale)}</dd></div><div><dt>{text.errorRate}</dt><dd>{Math.round(source.errorRate * 100)}%</dd></div><div><dt>{text.latestRun}</dt><dd>{lastRun ? <Link href={`/admin/collection-runs/${lastRun.id}`}>{lastRun.id}</Link> : "—"}</dd></div></dl></section><section><h2>{text.configuration}</h2><dl className="detail-list"><div><dt>{text.lifecycle}</dt><dd><StatusPill value={source.lifecycle} locale={locale} /></dd></div><div><dt>{text.environments}</dt><dd>{source.environments.join(" / ") || "—"}</dd></div><div><dt>{text.acquisition}</dt><dd>{source.acquisitionMethod}</dd></div><div><dt>{text.capabilities}</dt><dd>{source.capabilities.map((item) => `${item.capability}@${item.version}`).join(" / ") || "—"}</dd></div></dl></section><section className="source-coverage-section"><h2>{text.coverage}</h2><dl className="data-explorer-summary"><div><dt>{text.runs}</dt><dd>{source._count.collectionRuns}</dd></div><div><dt>{text.events}</dt><dd>{source._count.sourceEventOccurrences}</dd></div><div><dt>{text.signals}</dt><dd>{source._count.sourceMarketSignals}</dd></div><div><dt>{text.rates}</dt><dd>{source._count.observations}</dd></div><div><dt>{text.targets}</dt><dd>{source._count.crawlTargets}</dd></div></dl></section></div>,
    runs: <AdminTable columns={[{ key: "run", label: text.run }, { key: "mode", label: text.mode }, { key: "status", label: text.status }, { key: "records", label: text.records }, { key: "incident", label: text.incident }, { key: "started", label: text.started }]} rows={runs.map((run) => ({ id: run.id, href: `/admin/collection-runs/${run.id}`, cells: { run: <span className="code-value">{run.id}</span>, mode: run.mode, status: <StatusPill value={run.status} locale={locale} />, records: `${run.successCount} / ${run.failureCount}`, incident: run.incident ? <><StatusPill value={run.incident.severity} locale={locale} /> <StatusPill value={run.incident.status} locale={locale} /></> : "—", started: date(run.startedAt ?? run.createdAt, locale) } }))} emptyTitle={text.noRuns} emptyBody={text.noRunsBody} />,
    schedules: <AdminTable columns={[{ key: "workflow", label: text.workflow }, { key: "queue", label: text.queue }, { key: "frequency", label: text.frequency }, { key: "status", label: text.status }, { key: "last", label: text.lastQueued }, { key: "next", label: text.nextRun }]} rows={sourceSchedules.map((schedule) => ({ id: schedule.id, cells: { workflow: <><strong>{schedule.key}</strong><small>{schedule.jobType}</small></>, queue: schedule.queueName, frequency: schedule.cronExpression, status: <StatusPill value={schedule.enabled ? "ENABLED" : "DISABLED"} locale={locale} />, last: date(schedule.lastEnqueuedAt, locale), next: date(schedule.nextRunAt, locale) } }))} emptyTitle={text.noSchedules} emptyBody={text.noSchedulesBody} />,
    frontier: <AdminTable columns={[{ key: "url", label: "URL" }, { key: "kind", label: text.kind }, { key: "status", label: text.status }, { key: "failures", label: text.failures }, { key: "last", label: text.lastFetched }, { key: "next", label: text.nextFetch }]} rows={frontier.map((target) => ({ id: target.id, cells: { url: <span className="code-value">{target.url}</span>, kind: target.kind, status: <StatusPill value={target.active ? target.status : "INACTIVE"} locale={locale} />, failures: target.consecutiveFailures, last: date(target.lastFetchedAt, locale), next: date(target.nextFetchAt, locale) } }))} emptyTitle={text.noTargets} emptyBody={text.noTargetsBody} />,
    data: <SourceData locale={locale} sourceKey={source.key} events={recentEvents} signals={recentSignals} text={text} />,
  };
  return <section className="admin-page data-source-detail-page">
    <AdminPageHeader title={source.name} description={source.key} actions={<div className="header-pills"><StatusPill value={source.enabled ? source.operationalStatus : "PAUSED"} locale={locale} /><Link className="button button-secondary" href="/admin/data-sources">{text.back}</Link></div>} />
    <nav className="data-explorer-tabs source-detail-tabs" aria-label={text.sections}>{tabs.map((item) => <Link key={item} href={`/admin/data-sources/${source.key}?tab=${item}`} aria-current={tab === item ? "page" : undefined}>{text.tabs[item]}{item === "runs" ? <span>{source._count.collectionRuns}</span> : item === "frontier" ? <span>{source._count.crawlTargets}</span> : null}</Link>)}</nav>
    <div className="source-tab-content">{tabContent[tab]}</div>
  </section>;
}

function SourceData({ locale, sourceKey, events, signals, text }: { locale: AdminLocale; sourceKey: string; events: Array<{ id: string; title: string; city: string | null; startsAt: Date; status: string }>; signals: Array<{ id: string; title: string; region: string; startsAt: Date; direction: string }>; text: ReturnType<typeof copy> }) {
  const tables: Array<{ title: string; columns: AdminColumn[]; rows: AdminRow[] }> = [
    { title: text.latestEvents, columns: [{ key: "record", label: text.event }, { key: "location", label: text.location }, { key: "starts", label: text.started }, { key: "status", label: text.status }], rows: events.map((item) => ({ id: item.id, cells: { record: item.title, location: item.city ?? "—", starts: date(item.startsAt, locale), status: <StatusPill value={item.status} locale={locale} /> } })) },
    { title: text.latestSignals, columns: [{ key: "record", label: text.signal }, { key: "location", label: text.location }, { key: "starts", label: text.started }, { key: "status", label: text.direction }], rows: signals.map((item) => ({ id: item.id, cells: { record: item.title, location: item.region, starts: date(item.startsAt, locale), status: <StatusPill value={item.direction} locale={locale} /> } })) },
  ];
  return <div className="source-data-sections">{tables.map((table) => <section key={table.title}><header className="collection-section-header"><div><h2>{table.title}</h2></div><Link href={`/admin/data-explorer?layer=source&source=${sourceKey}`}>{text.openExplorer}</Link></header><AdminTable columns={table.columns} rows={table.rows} emptyTitle={text.noData} emptyBody={text.noDataBody} /></section>)}</div>;
}

function jsonObject(value: Prisma.JsonValue): Record<string, Prisma.JsonValue> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, Prisma.JsonValue> : {}; }
function stringValue(value: Prisma.JsonValue | undefined) { return typeof value === "string" ? value : ""; }
function date(value: Date | null, locale: AdminLocale) { return value ? value.toLocaleString(adminDateLocale(locale), { dateStyle: "medium", timeStyle: "short", timeZone: "Pacific/Auckland" }) : "—"; }
function copy(locale: AdminLocale) { return locale === "zh" ? zh : en; }
const en = { back: "Back to data sources", sections: "Source workspace sections", tabs: { overview: "Overview", runs: "Runs", schedules: "Schedules", frontier: "Crawl frontier", data: "Data" }, operationalState: "Operational state", collectionState: "Collection state", health: "Health", lastSuccess: "Last success", errorRate: "Error rate", latestRun: "Latest run", configuration: "Configuration", lifecycle: "Lifecycle", environments: "Environments", acquisition: "Acquisition method", capabilities: "Capabilities", coverage: "Collected coverage", runs: "Runs", events: "Events", signals: "Signals", rates: "Rates", targets: "Targets", run: "Collection run", mode: "Mode", status: "Status", records: "Success / failure", incident: "Incident", started: "Started", noRuns: "No collection runs", noRunsBody: "This source has not produced a collection run.", workflow: "Workflow", queue: "Queue", frequency: "Frequency", lastQueued: "Last queued", nextRun: "Next run", noSchedules: "No schedules", noSchedulesBody: "No collection schedule is configured for this source.", kind: "Kind", failures: "Failures", lastFetched: "Last fetched", nextFetch: "Next fetch", noTargets: "No crawl targets", noTargetsBody: "This source has not discovered any crawl targets.", latestEvents: "Latest source events", latestSignals: "Latest source signals", event: "Event", signal: "Signal", location: "Location", direction: "Direction", openExplorer: "Open in Data Explorer", noData: "No source data", noDataBody: "This source has not produced records of this type." };
const zh: typeof en = { back: "返回数据来源", sections: "来源工作区栏目", tabs: { overview: "概览", runs: "运行", schedules: "计划", frontier: "抓取前沿", data: "数据" }, operationalState: "运行状态", collectionState: "采集状态", health: "健康状态", lastSuccess: "最近成功", errorRate: "错误率", latestRun: "最近运行", configuration: "配置信息", lifecycle: "生命周期", environments: "适用环境", acquisition: "获取方式", capabilities: "来源能力", coverage: "采集覆盖", runs: "运行", events: "事件", signals: "信号", rates: "价格", targets: "目标", run: "采集运行", mode: "模式", status: "状态", records: "成功 / 失败", incident: "异常", started: "开始时间", noRuns: "暂无采集运行", noRunsBody: "此来源尚未产生采集运行。", workflow: "采集流程", queue: "队列", frequency: "频率", lastQueued: "最近入队", nextRun: "下次运行", noSchedules: "暂无计划", noSchedulesBody: "此来源尚未配置采集计划。", kind: "类型", failures: "失败次数", lastFetched: "最近抓取", nextFetch: "下次抓取", noTargets: "暂无抓取目标", noTargetsBody: "此来源尚未发现抓取目标。", latestEvents: "最近来源事件", latestSignals: "最近来源信号", event: "事件", signal: "信号", location: "地点", direction: "方向", openExplorer: "在数据浏览器中打开", noData: "暂无来源数据", noDataBody: "此来源尚未产生该类型记录。" };
