ALTER TYPE "MarketSignalType" ADD VALUE IF NOT EXISTS 'TOURISM_DEMAND';
ALTER TYPE "MarketSignalType" ADD VALUE IF NOT EXISTS 'TRANSPORT_FLOW';
ALTER TYPE "MarketSignalType" ADD VALUE IF NOT EXISTS 'FX_RATE';
