import { prisma, type Prisma, type RiskCaseStatus } from "@tymra/db";

import { AdminListTools } from "@/components/admin/AdminListControls";
import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminListSummary, AdminPagination, AdminTable, StatusPill } from "@/components/admin/AdminTable";
import { formatAdminValue } from "@/lib/admin-i18n";
import { adminListHref, adminListState } from "@/lib/admin-list";
import { getAdminLocale } from "@/lib/server/admin-locale";

const statuses: RiskCaseStatus[] = ["OPEN", "APPROVED", "DENIED", "RESOLVED"];

export default async function MembershipRiskPage({ searchParams }: { searchParams: Record<string, string | undefined> }) {
  const locale = getAdminLocale(); const t = locale === "zh" ? zh : en; const since = new Date(Date.now() - 30 * 86_400_000); const { page, pageSize, skip } = adminListState(searchParams); const q = searchParams.q?.trim().slice(0, 100) ?? ""; const status = statuses.includes(searchParams.status as RiskCaseStatus) ? searchParams.status as RiskCaseStatus : undefined;
  const base: Prisma.MembershipRiskCaseWhereInput = { createdAt: { gte: since } }; const where: Prisma.MembershipRiskCaseWhereInput = { ...base, ...(status ? { status } : {}), ...(q ? { OR: [{ customerUserId: { contains: q, mode: "insensitive" } }, { action: { contains: q, mode: "insensitive" } }] } : {}) };
  const [total, summaryCases, cases] = await Promise.all([prisma.membershipRiskCase.count({ where }), prisma.membershipRiskCase.findMany({ where: base, orderBy: { createdAt: "desc" }, take: 1000, select: { status: true, appealReason: true, reasonCodes: true } }), prisma.membershipRiskCase.findMany({ where, orderBy: { createdAt: "desc" }, skip, take: pageSize })]);
  const open = summaryCases.filter((item) => item.status === "OPEN").length; const appealed = summaryCases.filter((item) => item.appealReason).length; const approved = summaryCases.filter((item) => item.status === "APPROVED").length; const reviewed = summaryCases.filter((item) => ["APPROVED", "DENIED"].includes(item.status)).length;
  const topReasons = [...summaryCases.reduce((map, item) => { if (Array.isArray(item.reasonCodes)) for (const reason of item.reasonCodes) if (typeof reason === "string") map.set(reason, (map.get(reason) ?? 0) + 1); return map; }, new Map<string, number>()).entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
  return <section className="admin-page"><AdminPageHeader title={t.title} description={t.description} /><section className="admin-stat-grid"><article><span>{t.cases}</span><strong>{summaryCases.length}</strong></article><article><span>{t.open}</span><strong>{open}</strong></article><article><span>{t.appealed}</span><strong>{appealed}</strong></article><article><span>{t.rate}</span><strong>{reviewed ? `${Math.round(approved / reviewed * 100)}%` : "—"}</strong></article></section><section className="admin-detail-section"><div className="admin-section-heading"><h2>{t.reasons}</h2></div><div className="risk-reason-list">{topReasons.map(([reason, count]) => <span key={reason}><strong>{formatAdminValue(locale, reason)}</strong><em>{count}</em></span>)}</div></section><form className="admin-filters" method="get"><label>{t.search}<input name="q" defaultValue={q} placeholder={t.searchPlaceholder} /></label><label>{t.status}<select name="status" defaultValue={status ?? ""}><option value="">{t.allStatuses}</option>{statuses.map((value) => <option value={value} key={value}>{formatAdminValue(locale, value)}</option>)}</select></label><button className="button button-secondary" type="submit">{t.apply}</button></form><AdminListSummary locale={locale} total={total} tools={<AdminListTools locale={locale} viewName={t.title} />} /><AdminTable columns={[{ key: "customer", label: t.customer }, { key: "action", label: t.action }, { key: "outcome", label: t.outcome }, { key: "status", label: t.status }, { key: "reasons", label: t.reasons }]} rows={cases.map((item) => ({ id: item.id, href: item.customerUserId ? `/admin/customers/${item.customerUserId}` : undefined, cells: { customer: item.customerUserId ? <><strong>{t.reviewCustomer}</strong><small>{item.customerUserId}</small></> : "—", action: formatAdminValue(locale, item.action), outcome: formatAdminValue(locale, item.outcome), status: <StatusPill value={item.status} locale={locale} />, reasons: Array.isArray(item.reasonCodes) ? item.reasonCodes.filter((reason): reason is string => typeof reason === "string").map((reason) => formatAdminValue(locale, reason)).join(", ") : "—" } }))} emptyTitle={t.empty} emptyBody={t.emptyBody} /><AdminPagination locale={locale} page={page} pageSize={pageSize} total={total} href={(next, size = pageSize) => adminListHref("/admin/membership-risk", searchParams, { page: Math.max(1, next), pageSize: size })} /></section>;
}
const en = { title: "Membership risk", description: "Calibrate challenges, cooldowns, duplicate benefits and reviews by reason code; shared IP never blocks on its own.", cases: "30-day cases", open: "Open", appealed: "Appealed", rate: "Review approval rate", reasons: "Top reason codes", search: "Search", searchPlaceholder: "Customer ID or action", status: "Status", allStatuses: "All statuses", apply: "Apply filters", customer: "Customer", reviewCustomer: "Review customer", action: "Action", outcome: "Outcome", empty: "No risk cases", emptyBody: "No risk cases match these filters." };
const zh: typeof en = { title: "会员风控", description: "按原因码校准挑战、冷却、重复权益与人工复核；共享 IP 不会单独触发封禁。", cases: "30 天案件", open: "待处理", appealed: "已申诉", rate: "复核放行率", reasons: "主要原因", search: "搜索", searchPlaceholder: "客户 ID 或动作", status: "状态", allStatuses: "全部状态", apply: "应用筛选", customer: "客户", reviewCustomer: "查看客户", action: "动作", outcome: "结果", empty: "近 30 天没有风控案件", emptyBody: "没有符合当前筛选条件的案件。" };
