import { prisma, type Prisma } from "@tymra/db";

import { AdminListTools } from "@/components/admin/AdminListControls";
import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminListSummary, AdminPagination, AdminTable, StatusPill } from "@/components/admin/AdminTable";
import { adminDateLocale } from "@/lib/admin-i18n";
import { adminListHref, adminListState } from "@/lib/admin-list";
import { getAdminLocale } from "@/lib/server/admin-locale";

export default async function BillingEventsPage({ searchParams }: { searchParams: Record<string, string | undefined> }) {
  const locale = getAdminLocale(); const t = locale === "zh" ? zh : en; const { page, pageSize, skip } = adminListState(searchParams); const q = searchParams.q?.trim().slice(0, 100) ?? ""; const processing = ["processed", "pending", "failed"].includes(searchParams.processing ?? "") ? searchParams.processing : undefined;
  const where: Prisma.StripeBillingEventWhereInput = { ...(q ? { OR: [{ stripeEventId: { contains: q, mode: "insensitive" } }, { eventType: { contains: q, mode: "insensitive" } }, { processingError: { contains: q, mode: "insensitive" } }] } : {}), ...(processing === "processed" ? { processedAt: { not: null }, processingError: null } : processing === "failed" ? { processingError: { not: null } } : processing === "pending" ? { processedAt: null, processingError: null } : {}) };
  const [total, records] = await Promise.all([prisma.stripeBillingEvent.count({ where }), prisma.stripeBillingEvent.findMany({ where, orderBy: { createdAt: "desc" }, skip, take: pageSize })]);
  return <section className="admin-page"><AdminPageHeader title={t.title} description={t.description} /><form className="admin-filters" method="get"><label>{t.search}<input name="q" defaultValue={q} placeholder={t.searchPlaceholder} /></label><label>{t.processing}<select name="processing" defaultValue={processing ?? ""}><option value="">{t.allProcessing}</option><option value="processed">{t.processed}</option><option value="pending">{t.pending}</option><option value="failed">{t.failed}</option></select></label><button className="button button-secondary" type="submit">{t.apply}</button></form><AdminListSummary locale={locale} total={total} tools={<AdminListTools locale={locale} viewName={t.title} />} /><AdminTable columns={[{ key: "event", label: t.event }, { key: "type", label: t.type }, { key: "status", label: t.processing }, { key: "error", label: t.error }, { key: "created", label: t.received }]} rows={records.map((item) => ({ id: item.id, cells: { event: <><strong>{item.eventType}</strong><small>{item.stripeEventId}</small></>, type: item.eventType, status: <StatusPill value={item.processingError ? "FAILED" : item.processedAt ? "PROCESSED" : "PENDING"} locale={locale} />, error: item.processingError ?? "—", created: item.createdAt.toLocaleString(adminDateLocale(locale), { timeZone: "Pacific/Auckland" }) } }))} emptyTitle={t.empty} emptyBody={t.emptyBody} /><AdminPagination locale={locale} page={page} pageSize={pageSize} total={total} href={(next, size = pageSize) => adminListHref("/admin/billing-events", searchParams, { page: Math.max(1, next), pageSize: size })} /></section>;
}
const en = { title: "Billing events", description: "Event identity, processing state and errors without secrets or full payment payloads.", search: "Search", searchPlaceholder: "Event ID, type or error", processing: "Processing", allProcessing: "All processing states", processed: "Processed", pending: "Pending", failed: "Failed", apply: "Apply filters", event: "Event", type: "Type", error: "Error", received: "Received", empty: "No billing events", emptyBody: "No billing events match these filters." };
const zh: typeof en = { title: "计费事件", description: "只显示事件身份、处理状态和错误；不显示密钥或完整付款载荷。", search: "搜索", searchPlaceholder: "事件 ID、类型或错误", processing: "处理状态", allProcessing: "全部处理状态", processed: "已处理", pending: "待处理", failed: "失败", apply: "应用筛选", event: "事件", type: "类型", error: "错误", received: "收到时间", empty: "没有计费事件", emptyBody: "没有符合当前筛选条件的计费事件。" };
