import { prisma } from "@tymra/db";
import Link from "next/link";
import { notFound } from "next/navigation";

import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminTable, StatusPill } from "@/components/admin/AdminTable";
import { adminDateLocale, type AdminLocale } from "@/lib/admin-i18n";
import { getAdminLocale } from "@/lib/server/admin-locale";

export default async function AccommodationDetailPage({ params }: { params: { propertyId: string } }) {
  const locale = getAdminLocale();
  const text = locale === "zh" ? zh : en;
  const property = await prisma.property.findUnique({ where: { id: params.propertyId }, include: { units: { where: { isDemo: false }, orderBy: { officialName: "asc" }, include: { _count: { select: { listings: true, priceChecks: true, targetRelationships: true } } } }, listings: { where: { isDemo: false }, orderBy: { firstDiscoveredAt: "desc" }, include: { unit: { select: { officialName: true } }, dataSource: { select: { name: true } } } }, priceChecks: { where: { isDemo: false }, orderBy: { createdAt: "desc" }, take: 20, include: { unit: { select: { officialName: true } } } } } });
  if (!property || property.isDemo) notFound();
  const relationships = await prisma.competitorRelationship.findMany({ where: { isDemo: false, targetUnit: { propertyId: property.id }, validTo: null }, orderBy: [{ targetUnitId: "asc" }, { role: "asc" }], include: { targetUnit: { select: { officialName: true } }, competitorUnit: { include: { property: { select: { id: true, canonicalName: true } } } } } });
  const unitRows = property.units.map((unit) => ({ id: unit.id, cells: { unit: <span id={`unit-${unit.id}`}><strong>{unit.officialName}</strong><small>{unit.canonicalName}</small></span>, type: unit.unitType, capacity: unit.capacity, rooms: `${unit.bedrooms ?? "—"} / ${unit.bathrooms ?? "—"}`, status: <StatusPill value={unit.status} locale={locale} />, listings: unit._count.listings, checks: `${unit._count.priceChecks} / ${unit._count.targetRelationships}` } }));
  const listingRows = property.listings.map((listing) => ({ id: listing.id, href: listing.canonicalUrl || listing.url, cells: { listing: <><strong>{listing.platformUnitName}</strong><small>{listing.externalId}</small></>, unit: listing.unit.officialName, source: listing.dataSource.name, platform: listing.platform, status: <StatusPill value={listing.onlineStatus} locale={locale} />, confirmed: date(listing.lastConfirmedAt, locale) } }));
  const relationshipRows = relationships.map((relationship) => ({ id: relationship.id, href: `/admin/accommodations/${relationship.competitorUnit.property.id}`, cells: { target: relationship.targetUnit.officialName, competitor: <><strong>{relationship.competitorUnit.property.canonicalName}</strong><small>{relationship.competitorUnit.officialName}</small></>, role: <StatusPill value={relationship.role} locale={locale} />, reason: relationship.reasonCode, source: relationship.manualOverride ? text.manual : relationship.suggestedBy } }));
  const checkRows = property.priceChecks.map((check) => ({ id: check.id, href: `/admin/checks/${check.id}`, cells: { check: <span className="code-value">{check.id}</span>, unit: check.unit?.officialName ?? text.unconfirmed, status: <StatusPill value={check.status} locale={locale} />, market: check.marketKey, created: date(check.createdAt, locale) } }));

  return <section className="admin-page accommodation-detail-page">
    <AdminPageHeader title={property.canonicalName} description={property.address} actions={<div className="header-pills"><StatusPill value={property.supportStatus} locale={locale} /><Link className="button button-secondary" href="/admin/accommodations">{text.back}</Link></div>} />
    <dl className="run-summary"><div><dt>{text.city}</dt><dd>{property.city}</dd></div><div><dt>{text.region}</dt><dd>{property.region ?? "—"}</dd></div><div><dt>{text.type}</dt><dd>{property.accommodationType}</dd></div><div><dt>{text.units}</dt><dd>{property.units.length}</dd></div><div><dt>{text.confidence}</dt><dd>{Math.round(property.identityConfidence * 100)}%</dd></div></dl>
    <div className="detail-sections accommodation-detail-sections">
      <section><h2>{text.units}</h2><AdminTable columns={[{ key: "unit", label: text.unit }, { key: "type", label: text.type }, { key: "capacity", label: text.capacity }, { key: "rooms", label: text.bedBath }, { key: "status", label: text.status }, { key: "listings", label: text.listings }, { key: "checks", label: text.checksCompetitors }]} rows={unitRows} emptyTitle={text.noUnits} emptyBody={text.noUnitsBody} /></section>
      <section><h2>{text.listings}</h2><AdminTable columns={[{ key: "listing", label: text.listing }, { key: "unit", label: text.unit }, { key: "source", label: text.source }, { key: "platform", label: text.platform }, { key: "status", label: text.status }, { key: "confirmed", label: text.confirmed }]} rows={listingRows} emptyTitle={text.noListings} emptyBody={text.noListingsBody} /></section>
      <section><h2>{text.competitors}</h2><AdminTable columns={[{ key: "target", label: text.targetUnit }, { key: "competitor", label: text.competitor }, { key: "role", label: text.role }, { key: "reason", label: text.reason }, { key: "source", label: text.source }]} rows={relationshipRows} emptyTitle={text.noCompetitors} emptyBody={text.noCompetitorsBody} /></section>
      <section><h2>{text.recentChecks}</h2><AdminTable columns={[{ key: "check", label: text.check }, { key: "unit", label: text.unit }, { key: "status", label: text.status }, { key: "market", label: text.market }, { key: "created", label: text.created }]} rows={checkRows} emptyTitle={text.noChecks} emptyBody={text.noChecksBody} /></section>
    </div>
  </section>;
}

function date(value: Date | null, locale: AdminLocale) { return value ? value.toLocaleString(adminDateLocale(locale), { dateStyle: "medium", timeStyle: "short", timeZone: "Pacific/Auckland" }) : "—"; }
const en = { back: "Back to properties & units", city: "City", region: "Region", type: "Type", units: "Sellable units", confidence: "Identity confidence", unit: "Unit", capacity: "Capacity", bedBath: "Bedrooms / bathrooms", status: "Status", listings: "Platform listings", checksCompetitors: "Checks / competitors", noUnits: "No sellable units", noUnitsBody: "No room types are mapped to this property.", listing: "Listing", source: "Source", platform: "Platform", confirmed: "Last confirmed", noListings: "No platform listings", noListingsBody: "No provider listings are mapped to this property.", competitors: "Competitor relationships", targetUnit: "Target unit", competitor: "Competitor", role: "Role", reason: "Reason", manual: "Manual override", noCompetitors: "No competitor relationships", noCompetitorsBody: "No active comparable relationships are configured.", recentChecks: "Recent price checks", check: "Price check", market: "Market", created: "Created", unconfirmed: "Unconfirmed unit", noChecks: "No price checks", noChecksBody: "No customer price checks are linked to this property." };
const zh: typeof en = { back: "返回房源与房型", city: "城市", region: "地区", type: "类型", units: "可售房型", confidence: "身份置信度", unit: "房型", capacity: "容纳人数", bedBath: "卧室 / 卫生间", status: "状态", listings: "平台房源", checksCompetitors: "检查 / 竞品", noUnits: "暂无可售房型", noUnitsBody: "此房源尚未映射房型。", listing: "平台房源", source: "来源", platform: "平台", confirmed: "最后确认", noListings: "暂无平台房源", noListingsBody: "此房源尚未映射平台房源。", competitors: "竞品关系", targetUnit: "目标房型", competitor: "竞品", role: "角色", reason: "原因", manual: "人工覆盖", noCompetitors: "暂无竞品关系", noCompetitorsBody: "尚未配置有效的可比关系。", recentChecks: "最近价格检查", check: "价格检查", market: "市场", created: "创建时间", unconfirmed: "未确认房型", noChecks: "暂无价格检查", noChecksBody: "没有关联到此房源的客户价格检查。" };
