import { prisma, type MembershipPlan, type MembershipSubscriptionStatus, type Prisma } from "@tymra/db";

import { AdminListTools } from "@/components/admin/AdminListControls";
import { AdminPageHeader } from "@/components/admin/AdminResourcePage";
import { AdminListSummary, AdminPagination, AdminTable, StatusPill } from "@/components/admin/AdminTable";
import { adminDateLocale, formatAdminValue } from "@/lib/admin-i18n";
import { adminListHref, adminListState } from "@/lib/admin-list";
import { getAdminLocale } from "@/lib/server/admin-locale";

const plans: MembershipPlan[] = ["FREE", "HOST", "PRO", "PORTFOLIO"];
const statuses: MembershipSubscriptionStatus[] = ["ACTIVE", "PAST_DUE", "CANCELLED", "INCOMPLETE", "PAUSED"];

export default async function MembershipsPage({ searchParams }: { searchParams: Record<string, string | undefined> }) {
  const locale = getAdminLocale(); const t = locale === "zh" ? zh : en; const { page, pageSize, skip } = adminListState(searchParams);
  const q = searchParams.q?.trim().slice(0, 100) ?? ""; const plan = plans.includes(searchParams.plan as MembershipPlan) ? searchParams.plan as MembershipPlan : undefined; const status = statuses.includes(searchParams.status as MembershipSubscriptionStatus) ? searchParams.status as MembershipSubscriptionStatus : undefined;
  const where: Prisma.MembershipSubscriptionWhereInput = { ...(plan ? { plan } : {}), ...(status ? { status } : {}), ...(q ? { customerUserId: { contains: q, mode: "insensitive" } } : {}) };
  const [total, records] = await Promise.all([prisma.membershipSubscription.count({ where }), prisma.membershipSubscription.findMany({ where, orderBy: { updatedAt: "desc" }, skip, take: pageSize, include: { customerUser: { select: { id: true, status: true } } } })]);
  return <section className="admin-page"><AdminPageHeader title={t.title} description={t.description} /><form className="admin-filters" method="get"><label>{t.search}<input name="q" defaultValue={q} placeholder={t.searchPlaceholder} /></label><label>{t.plan}<select name="plan" defaultValue={plan ?? ""}><option value="">{t.allPlans}</option>{plans.map((value) => <option key={value}>{value}</option>)}</select></label><label>{t.status}<select name="status" defaultValue={status ?? ""}><option value="">{t.allStatuses}</option>{statuses.map((value) => <option value={value} key={value}>{formatAdminValue(locale, value)}</option>)}</select></label><button className="button button-secondary" type="submit">{t.apply}</button></form><AdminListSummary locale={locale} total={total} tools={<AdminListTools locale={locale} viewName={t.title} />} /><AdminTable columns={[{ key: "customer", label: t.customer }, { key: "plan", label: t.plan }, { key: "status", label: t.status }, { key: "pending", label: t.pending }, { key: "period", label: t.period }]} rows={records.map((item) => ({ id: item.id, href: `/admin/customers/${item.customerUserId}`, cells: { customer: <><strong>{item.customerUser.status === "ACTIVE" ? t.activeCustomer : formatAdminValue(locale, item.customerUser.status)}</strong><small>{item.customerUserId}</small></>, plan: item.plan, status: <StatusPill value={item.status} locale={locale} />, pending: item.pendingPlan ?? "—", period: item.currentPeriodEnd ? item.currentPeriodEnd.toLocaleString(adminDateLocale(locale), { timeZone: "Pacific/Auckland" }) : "—" } }))} emptyTitle={t.empty} emptyBody={t.emptyBody} /><AdminPagination locale={locale} page={page} pageSize={pageSize} total={total} href={(next, size = pageSize) => adminListHref("/admin/memberships", searchParams, { page: Math.max(1, next), pageSize: size })} /></section>;
}
const en = { title: "Memberships", description: "Review plans, billing periods, payment grace and pending changes.", search: "Search", searchPlaceholder: "Customer ID", plan: "Plan", allPlans: "All plans", status: "Status", allStatuses: "All statuses", apply: "Apply filters", customer: "Customer", activeCustomer: "Active customer", pending: "Pending change", period: "Period end", empty: "No memberships", emptyBody: "No membership records match these filters." };
const zh: typeof en = { title: "会员状态", description: "核对方案、周期、付款宽限和待生效变更。", search: "搜索", searchPlaceholder: "客户 ID", plan: "方案", allPlans: "全部方案", status: "状态", allStatuses: "全部状态", apply: "应用筛选", customer: "客户", activeCustomer: "有效客户", pending: "待生效", period: "周期结束", empty: "没有会员记录", emptyBody: "没有符合当前筛选条件的会员记录。" };
